#该配置文件在这里不起作用可以忽略
server:
  port: 8080

# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mbg?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  # springboot 2.4 swagger之后版本需要添加以下配置否则报错
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# MyBatis mapper.xml路径配置
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:mapper/*.xml
