#springboot整合mybatis配置
#数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

#应用配置
server:
  port: 8080
  servlet:
    context-path: /mybatis
  tomcat:
    uri-encoding: UTF-8


#Mybatis配置
mybatis:
  type-aliases-package: com.ac.springboot.mybatis.domain
  mapper-locations: classpath:mapper/*.xml
