# Server Config
server:
  port: 8080
  servlet:
    context-path: /mybatis
  tomcat:
    uri-encoding: UTF-8

# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_plus?useUnicode=true&characterEncoding=utf8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

# sql输出日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 全局设置主键生成策略，一般不配置使用默认即可ASSIGN_ID
      id-type: auto

